### ISSUE TITLE
Firefox overflow Menu overlaps

### ISSUE THREAD

**Issue by Acid-Crash** [freaktechnik/advanced-github-notifier#115] opened 2019-07-16 07:35 UTC
Hi here.
Firefox 68 Win10x64 Advanced GitHub Notifier 1.5.0
There is a bug related to text overlap when extensions button is placed inside overflow menu
![image](https://user-images.githubusercontent.com/32600318/61274421-762b1e80-a7b4-11e9-8919-a0d61bce40ed.png)

P.S. I did notice similar bugs however none of them were referring to overflow menu

**Comment by freaktechnik** [comment] 2019-07-16 18:55
It's all exactly the same CSS issue (plus this is the fixed-width popup) :) Duplicate of #7 .

**Closed by freaktechnik** 2019-07-16 18:55 UTC
