### ISSUE TITLE
visual bug when icon is placed in menu

### ISSUE THREAD

**Issue by tooomm** [freaktechnik/advanced-github-notifier#64] opened 2017-11-24 07:58 UTC
If placed in the normal UI, all is good:
![good](https://user-images.githubusercontent.com/9874850/33199916-ab096a34-d0f2-11e7-8c1f-e318c916bc1d.png)
(don't be confused about the (1) in the notifications, I already started loading one of the issues in the background)

But if you place the icon within the menu, the fixed width makes the text unreadable, because it looks like the lines are fixed height as well and the text has to merge:
![bad](https://user-images.githubusercontent.com/9874850/33199959-dcd469b0-d0f2-11e7-9541-8dbd819688d2.png)

**Comment by freaktechnik** [comment] 2017-11-24 08:36
duplicate of #7

**Closed by freaktechnik** 2017-11-24 08:36 UTC

**Comment by tooomm** [comment] 2017-11-24 09:08
Oh yeah, sorry. Obviously we're talking about the same thing. :)
