### ISSUE TITLE
Feature Request: Compatibility with Chrome Browser

### ISSUE THREAD

**Issue by euxx** [freaktechnik/advanced-github-notifier#509] opened 2024-03-14 03:28 UTC
Hi, thanks for your hard work on this extension. It's quite convenient for everyday use.

I was wondering if there are any plans for making this extension compatible with the Chrome browser? I believe this would benefit many Chrome users.

I tried to find similar on Chrome.  The most similar one I found is https://github.com/sindresorhus/notifier-for-github ，but it can't direct access to the notifications.

So just to see if there's possible to adapt to Chrome.

**Comment by freaktechnik** [comment] 2024-03-14 16:38
Duplicate of #49

**Closed by freaktechnik** 2024-03-14 16:38 UTC
Labels: enhancement
