### ISSUE TITLE
Popup Entry height with long lenght names. 

### ISSUE THREAD

**Issue by Acid-Crash** [freaktechnik/advanced-github-notifier#103] opened 2019-01-28 14:35 UTC
Hi here.
FF 64.02, Extension v1.4.6, Win10x64 
I have noticed that when there is an notification from an item that has long name (2 or 3 lines) there line/element height (most noticable in hover state) is calculated incorrectly. It should be wider.
![default](https://user-images.githubusercontent.com/32600318/51842526-c0f5ce80-2319-11e9-9949-bfc7b44179ef.png)

**Comment by freaktechnik** [comment] 2019-01-28 14:37
Duplicate of #7

**Closed by freaktechnik** 2019-01-28 14:37 UTC
